from collections import OrderedDict

from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats = formats_female + formats_male

    # Names based on UK-wide statistics from
    # http://webarchive.nationalarchives.gov.uk/20160105160709/http://ons.gov.uk/ons/publications/re-reference-tables.html?edition=tcm%3A77-243767
    #
    # adapted by Bangor University's Language Technologies Unit based on frequency lists and
    # corpus-based statistical rankings of personal names found in Welsh-language texts
    # developed for its Cysill spelling and grammar checker https://www.cysgliad.com/cysill/arlein/

    first_names_male = (
        "Daniel",
        "Lewis",)

 

    welsh_first_names_male = (
        'Idris',
        'Llion',
        'Twm',
        'Bleddyn',
        'Arthur',
        'Macsen',
        'Aron',
        'Gerallt',
        'Rhodri',
        'Iestyn',
        'Idwal',
        'Gerwyn',
        'Elgan',
        'Meirion',
        'Dylan',
        'Osian',
        'Harri',
        'Iolo',
        'Trefor',
        'Tudur',
        'Peredur',
        'Endaf',
        'Ifan',
        'Ianto',
        'Rhys',
        'Eifion',
        'Elidir',
        'Ifor',
        'Wyn',
        'Gethin',
        'Arwel',
        'Emlyn',
        'Eurig',
        'Derfel',
        'Dafydd',
        'Gruffydd',
        'Siôn',
        'Emyr',
        'Arwyn',
        'Dyfan',
        'Tomos',
        'Gwyndaf',
        'Guto',
        'Geraint',
        'Bedwyr',
        'Gwion',
        'Emrys',
        'Gwilym',
        'Ioan',
        'Einion',
        'Elwyn',
        'Trystan',
        'Gwynfor',
        'Iorwerth',
        'Gwydion',
        'Aled',
        'Morgan',
        'Deiniol',
        'Goronwy',
        'Gruffudd',
        'Hywel',
        'Rhun',
        'Dilwyn',
        'Meredudd',
        'Elis',
        'Huw',
        'Elfed',
        'Alun',
        'Dyfrig',
        'Owain',
        'Ieuan',
        'Steffan',
        'Gareth',
        'Cai',
        'Jac',
        'Efan',
        'Eban',
        'Carwyn',
        'Dewi',
        'Bryn',
        'Rhidian',
        'Llŷr',
        'Llywelyn',
        'Meilir',
        'Deian',
        'Glyn',
        'Iwan',
        'Edryd',
        'Tecwyn',
        'Alwyn')

    first_names_female = (

        "Bethan")

    welsh_first_names_female = (
        'Cerys',
        'Rhian',
        'Leusa',
        'Catrin',
        'Erin',
        'Cadi',
        'Llio',
        'Alys',
        'Gwen',
        'Menna',
        'Annest',
        'Siân',
        'Rhiannon',
        'Dwynwen',
        'Eluned',
        'Olwen',
        'Lleuwen',
        'Gwenno',
        'Nest',
        'Sioned',
        'Morfudd',
        'Gwenllïan',
        'Lois',
        'Glenda',
        'Caryl',
        'Angharad',
        'Nanw',
        'Gwenda',
        'Gwladys',
        'Sara',
        'Carys',
        'Luned',
        'Lleucu',
        'Nerys',
        'Megan',
        'Mari',
        'Awen',
        'Siwan',
        'Mererid',
        'Esyllt',
        'Marged',
        'Hawys',
        'Mali',
        'Elena',
        'Sali',
        'Annes',
        'Eirian',
        'Nesta',
        'Tegwen',
        'Eryl',
        'Enid',
        'Teleri',
        'Manon',
        'Ceinwen',
        'Eirwen',
        'Tesni',
        'Anest',
        'Gwyneth',
        'Elen',
        'Mair',
        'Nia',
        'Mared',
        'Elliw',
        'Sara',
        'Lowri',
        'Myfanwy',
        'Anwen',
        'Eleri',
        'Elsi',
        'Branwen',
        'Beca',
        'Elinor',
        'Efa',
        'Betsan',
        'Einir',
        'Meinir',
        'Mabli',
        'Delyth',
        'Elin',
        'Awel',
        'Dilys',
        'Gwawr',
        'Non',
        'Seren',
        'Enfys',
        'Ffion',
        'Eira',
        'Lili',
        'Gwennan',
        'Llinos')
    
#    frequent_first_names = (
#   )

    first_names_male = welsh_first_names_male + first_names_male

    first_names_female = welsh_first_names_female + first_names_female

    first_names = first_names_male + first_names_female # + frequent_first_names

    last_names = OrderedDict(
        (
        ('Jôs', 0.09),
        ('Tomos', 2.99),
        ('Huws', 2.76),
        ('Lewis', 2.75),
        ('Morgan', 2.75),
        ('Siencyn', 0.67),
        ('Prys', 0.9),
        ('Gruffydd', 2.95),
        ('Parri', 1.80),
        ('Harri', 1.80),
        ('Rhys', 3.75),
        ('Puw', 1.64),
        ('Humphry', 0.64),
        ('Bowen', 0.64),
        ('Elis', 0.63),
        ('Llwyd', 0.61),
        ('Owain', 3.61),
        ('Hopcyn', 0.56),
        ('Watcyn', 0.56),
        ('Dafydd', 3.55),
        ('Sion', 0.54),
        ('Siôn', 0.54),
        ('Owain', 4.53),
        ('Befan', 1.53),
        ('Llywelyn', 0.5),
        ('Wyn', 2.5),
        ('Morgan', 1.5),
        ('Ffowc', 0.01),
        ('Arthur', 0.5),
        ('Tudur', 1.5),
        ('Einon', 0.09),
        ('Beinon', 2.2),
        ('Dafis', 1.03),
        ('Meredith', 1.01)
        ('Glyn', 2.83),
        ('Arwyn', 0.83),
        ('Meirion', 2.83),
        ('Trefor', 0.71),
        ('Gethin', 0.83),
        ('Tomos', 2.83),
        ('Emrys', 0.38),
        ('Gwilym', 0.83),
        ('Einion', 0.53),
        ('Gwynfor', 0.33),
        ('Mostyn', 1.83),
        ('Iwan', 1.99),
        ('Goronwy', 2.83),
        ('Hywel', 2.83),
        ('Prytherch', 2.33),
        ('Prydderch', 2.23),
        ('Alun', 1.81),
        ('Aled', 1.81),
        ('Bryn', 0.23),
        ('Ifan', 2.01),
        ('Talfryn', 0.02),
        ('Steffan', 1.67),
	('Rhisiart', 0.99),
        )
    )

    prefixes_female = ("Mrs", "Ms", "Miss", "Dr")
    prefixes_male = ("Mr", "Dr")
